package com.example.trymycat.mapper;

import com.example.trymycat.entity.Test1;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface Test1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test1
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test1
     *
     * @mbg.generated
     */
    int insert(Test1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test1
     *
     * @mbg.generated
     */
    int insertSelective(Test1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test1
     *
     * @mbg.generated
     */
    Test1 selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test1
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Test1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test1
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Test1 record);


    List<Test1> selectAll(int begin,int end);
}