package com.example.trymycat.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Test1 implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test1.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test1.number
     *
     * @mbg.generated
     */
    private BigDecimal number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test1.text
     *
     * @mbg.generated
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test1.date
     *
     * @mbg.generated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test1
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test1.id
     *
     * @return the value of test1.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test1.id
     *
     * @param id the value for test1.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test1.number
     *
     * @return the value of test1.number
     *
     * @mbg.generated
     */
    public BigDecimal getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test1.number
     *
     * @param number the value for test1.number
     *
     * @mbg.generated
     */
    public void setNumber(BigDecimal number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test1.text
     *
     * @return the value of test1.text
     *
     * @mbg.generated
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test1.text
     *
     * @param text the value for test1.text
     *
     * @mbg.generated
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test1.date
     *
     * @return the value of test1.date
     *
     * @mbg.generated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test1.date
     *
     * @param date the value for test1.date
     *
     * @mbg.generated
     */
    public void setDate(Date date) {
        this.date = date;
    }
}